name: sf-portfolio
favicon: null
layout_spectrum: 0.74626
typography_spectrum: 0.46308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#403936'
    - '#66605b'
    - '#a6a29e'
    - '#847e7b'
    - '#e0ddd5'
  brandStrength: 0
  lightness: 0.6316675678826869
  saturation: 0.31276577594690025
  rhythmicContrast: 0.75
purpose: []
